name: Authentication-windows
on: push
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SECRET_KEY }}
      - name: Set up git folder
        run: |
          env
          mkdir -p /usr/bin/git
          cd /usr/bin/git          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: main
          CLEAN: true
          FOLDER: .
          SSH: true
